# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Jupyter Book Template  # Pas dit aan naar jouw titel
author: Fien14655179  # Jouw naam of teamnaam

# Force re-execution of notebooks on each build
execute:
  execute_notebooks: force

# Define the name of the LaTeX output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/Fien14655179/nogeenkeer
  branch: main


# HTML en opmaak
html:
  use_issues_button: true
  use_repository_button: true
  baseurl: /nogeenkeer/  # Nodig voor correcte styling op GitHub Pages

# Launch knoppen (optioneel, kan je weghalen als je ze niet wil)
launch_buttons:
  binderhub_url: ""
  colab_url: "https://colab.research.google.com"
  jupyterhub_url: ""

# Extra sphinx instellingen
sphinx:
  extra_extensions:
    - "IPython.sphinxext.ipython_console_highlighting"  # Fix voor syntax highlighting
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js  # Plotly fix
